name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - uses: actions/checkout@v2

    - uses: chainguard-dev/actions/setup-chainctl@main
      with:
        environment: chainops.dev
        identity: 540cc3ad9d1fcba95c0e42d89542cce47393f596/d3475b130c8f909b

    - uses: ko-build/setup-ko@v0.6
    - env:
        KO_DOCKER_REPO: tmp.chainreg.biz/mattmoor.priv
      run: ko build --tags yolo --bare

#     - uses: sigstore/cosign-installer@main
#     - run: |
#         cosign copy tmp.chainreg.biz/mattmoor.priv:yolo tmp.chainreg.biz/mattmoor.pub

    - env:
        KO_DOCKER_REPO: tmp.chainreg.biz/mattmoor.pub
      run: ko build --tags yolo --bare
